import React from 'react';
import { Inquiry } from '../../types';

interface InquiryReportProps {
    inquiry: Inquiry;
}

export const InquiryReport: React.FC<InquiryReportProps> = ({ inquiry }) => {
    const reportDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });

    return (
        <div id={`report-${inquiry.id}`} className="bg-white p-16 text-slate-900 font-serif max-w-[850px] mx-auto shadow-2xl print:shadow-none print:p-0">
            {/* Header / Letterhead */}
            <div className="flex justify-between items-start border-b-4 border-slate-900 pb-8 mb-10">
                <div className="flex items-center gap-4">
                    <div className="w-16 h-16 bg-slate-900 rounded-xl flex items-center justify-center text-white text-3xl">
                        <i className="fas fa-shield-child"></i>
                    </div>
                    <div>
                        <h1 className="text-2xl font-black tracking-tighter uppercase leading-none">Sentinel Child</h1>
                        <p className="text-[10px] font-bold uppercase tracking-[0.2em] mt-1 text-slate-500">National Intelligence & Protection Portal</p>
                    </div>
                </div>
                <div className="text-right">
                    <div className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-1">Official Intelligence Report</div>
                    <div className="text-lg font-black font-sans">#{inquiry.id.slice(-8).toUpperCase()}</div>
                </div>
            </div>

            {/* Classification */}
            <div className="flex justify-center mb-10">
                <div className="border-x-2 border-slate-200 px-10 py-1 text-[10px] font-black uppercase tracking-[0.5em] text-red-600">
                    CONFIDENTIAL // FOR OFFICIAL USE ONLY
                </div>
            </div>

            {/* Metadata Grid */}
            <div className="grid grid-cols-2 gap-y-6 gap-x-12 mb-12 py-8 border-y border-slate-100">
                <div>
                    <label className="block text-[10px] uppercase font-black tracking-widest text-slate-400 mb-1">Subject / Reporter</label>
                    <div className="text-sm font-bold">{inquiry.name || 'ANONYMOUS SOURCE'}</div>
                </div>
                <div>
                    <label className="block text-[10px] uppercase font-black tracking-widest text-slate-400 mb-1">Assigned Department</label>
                    <div className="text-sm font-bold">{inquiry.department || 'GENERAL INTAKE'}</div>
                </div>
                <div>
                    <label className="block text-[10px] uppercase font-black tracking-widest text-slate-400 mb-1">Submission Vector</label>
                    <div className="text-sm font-bold uppercase">{inquiry.is_voice ? 'Voice Inquiry (STT Processed)' : 'Direct Data Entry'}</div>
                </div>
                <div>
                    <label className="block text-[10px] uppercase font-black tracking-widest text-slate-400 mb-1">Report Generated</label>
                    <div className="text-sm font-bold">{reportDate}</div>
                </div>
            </div>

            {/* Transcription Block */}
            <div className="space-y-6">
                <div>
                    <h2 className="text-xs font-black uppercase tracking-widest text-slate-900 mb-4 border-l-4 border-slate-900 pl-3">Incident Transcription / Statement</h2>
                    <div className="bg-slate-50 p-8 rounded-lg border border-slate-100 italic text-sm leading-relaxed text-slate-700 whitespace-pre-wrap min-h-[200px]">
                        "{inquiry.transcription || inquiry.message || 'No transcription data available for this case.'}"
                    </div>
                </div>

                <div className="pt-10 flex justify-between items-end border-t border-slate-100 mt-20">
                    <div className="space-y-4">
                        <div className="w-48 h-1 bg-slate-200"></div>
                        <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Authorized Investigator Signature</p>
                    </div>
                    <div className="text-right opacity-30 grayscale pointer-events-none">
                        <div className="w-24 h-24 bg-slate-900/10 rounded-full flex items-center justify-center text-4xl">
                            <i className="fas fa-stamp"></i>
                        </div>
                    </div>
                </div>
            </div>

            {/* Footer */}
            <div className="mt-12 text-center text-[8px] font-bold uppercase tracking-widest text-slate-300">
                This document is automatically generated by the Sentinel Intelligence Assistant.
                Any unauthorized reproduction or distribution is strictly prohibited under the National Security Act.
            </div>
        </div>
    );
};
